#!/bin/sh

# Build a program against scope libs to ensure it is installed properly
# (C) 2014 Canonical Ltd.
# Authors: Martin Pitt <martin.pitt@ubuntu.com>
#          Jussi Pakkanen <jussi.pakkanen@canonical.com>

set -e

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cp scopetest.cpp $WORKDIR
cd $WORKDIR

g++ -std=c++11 -o scopetest scopetest.cpp `pkg-config --cflags --libs libunity-scopes`
echo "Scope build: OK"
[ -x scopetest ]
./scopetest
echo "Scope run: OK"
